# Generated by Django 4.2.29 on 2026-03-24 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_deck_card_deck'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_sections', to='cards.deck')),
            ],
            options={
                'ordering': ['deck', 'order'],
            },
        ),
        migrations.CreateModel(
            name='GuideSectionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='cards.guidesection')),
            ],
        ),
    ]
