# Generated by Django 4.2.29 on 2026-03-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_guidesection_guidesectionprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='published',
            field=models.BooleanField(default=False, help_text='Show on homepage'),
        ),
    ]
