# Generated by Django 4.2.29 on 2026-03-24 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_category_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='guide_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='cards.guidesection'),
        ),
    ]
