# Generated by Django 4.2.29 on 2026-03-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_card_guide_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
    ]
