# Generated by Django 4.2.29 on 2026-03-26 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_progress_needs_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='question_type',
            field=models.CharField(choices=[('concept', 'Concept'), ('application', 'Application')], default='concept', max_length=20),
        ),
    ]
